### ISSUE TITLE
Yanmanga not working

### ISSUE THREAD

**Issue by blunderedbishop** [oxdz/ccdl#17]
Returns this error:
```
Downloading：
Decoding:
Traceback (most recent call last):
  File "yanmanga.py", line 171, in <module>
    Yanmaga(linkinfo, webdriver.Chrome()).downloader()
  File "yanmanga.py", line 162, in downloader
    img = Image.open(BytesIO(imgs[urls[x]]))
  File "\PIL\Image.py", line 3009, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000278412BFAC8>
```

**Comment by blunderedbishop** [comment]
The problem seems to be on line 89 of `yanmaga.py`. 
```urls.append('https:' + x.get('imageUrl'))``` should be changed to 
```urls.append(x.get('imageUrl'))```

**Comment by blunderedbishop** [comment]
To add to that, from what I've seen `selenium` is not required for Yanmaga. It is possible to get the `data-member-jwt` and the `comici-viewer-id` with `requests` and find them in the html with `BeautifulSoup`.
