### ISSUE TITLE
sunday webry

### ISSUE THREAD

**Issue by gyeolls** [oxdz/ccdl#23]
error report

源碼: https://github.com/oxdz/ccdl

如需登入（含*）請提前在程式啟動的瀏覽器中登入，並加載目標url（任意標籤頁）！

>>>>>>>>輸入exit退出<<<<<<<<

url: https://www.sunday-webry.com/episode/3269754496585663566
下載失敗!
Traceback (most recent call last):
  File "CcdlSimpleStarter.py", line 93, in <module>
  File "ccdl\sunday_webry.py", line 46, in downloader
  File "selenium\webdriver\remote\webdriver.py", line 636, in execute_script
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.JavascriptException: Message: javascript error: pages is not defined
  (Session info: chrome=86.0.4240.75)

how can I do?

**Comment by hulu-hulu** [comment]
If you missed it, you can email me.
