### ISSUE TITLE
yanmanga.jp租赁、购买内容下载

### ISSUE THREAD

**Issue by lasthm** [oxdz/ccdl#3]
请问yanmanga.jp上租赁、购买内容有办法下载吗？已经有账号购买了

**Comment by vircoys** [comment]
无法通过阅读器页面的链接下载？

**Comment by lasthm** [comment]
信息如下，已在启动的浏览器里登录并加载目标url

源碼: https://github.com/oxdz/ccdl

如需登入（含*）請提前在程式啟動的瀏覽器中登入，並加載目標url（任意標籤頁）！


DevTools listening on ws://127.0.0.1:61119/devtools/browser/568bf607-afea-41ff-9ba0-ddfdeb728011
[75528:74388:0713/123140.963:ERROR:device_event_log_impl.cc(214)] [12:31:40.963] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)

>>>>>>>>輸入exit退出<<<<<<<<

url: https://yanmaga.jp/comics/%E5%BD%BC%E5%A5%B3%E3%81%AE%E5%8F%8B%E9%81%94/399d3fed1a7526022a9d09a806e612d8
下載失敗!
Traceback (most recent call last):
  File "CcdlSimpleStarter.py", line 75, in <module>
    reader.downloader()
  File "C:\Users\lasthm\AppData\Roaming\Python\Python38\site-packages\ccdl-0.1.16-py3.8.egg\ccdl\yanmaga.py", line 140, in downloader
    view_id = self.get_comic_viewer_id(self._link_info.url)
  File "C:\Users\lasthm\AppData\Roaming\Python\Python38\site-packages\ccdl-0.1.16-py3.8.egg\ccdl\yanmaga.py", line 38, in get_comic_viewer_id
    comici_vid = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by vircoys** [comment]
输入url:  https://yanmaga.jp/ 
进入手动输入 comici-viewer-id 模式，使用浏览器的 DevTools 查找其值
F12 --> CTRL + F --> 输入 comici-viewer-id --> ENTER --> 取其值复制到 ccdl 的启动器中
![x](https://user-images.githubusercontent.com/40519857/125396583-5187d280-e3df-11eb-9837-8ae35a4eb810.png)

**Comment by lasthm** [comment]
下载成功了，谢谢大佬
